
# PlanAhead Launch Script for Post-Synthesis floorplanning, created by Project Navigator

create_project -name telA -dir "/home/fazia/Desktop/debug_fazia_code_roms/telA/planAhead_run_1" -part xc7k160tffg676-2
set_property design_mode GateLvl [get_property srcset [current_run -impl]]
set_property edif_top_file "/home/fazia/Desktop/debug_fazia_code_roms/telA/telescope.ngc" [ get_property srcset [ current_run ] ]
add_files -norecurse { {/home/fazia/Desktop/debug_fazia_code_roms/telA} {../telB/ipcore_dir} {../common/ipcore_dir} {ipcore_dir} }
add_files [list {../telB/ipcore_dir/ram_1kx15.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_256x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_2kx15.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_32x16_single.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_4kx14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/myfifo2.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/aligner_rom_128x8.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_256x14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_16x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_64x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_1kx24.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/aligner_ram_128x8.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_128x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_8kx14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_1kx14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/ram_32x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../telB/ipcore_dir/myfifo.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_1kx15.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/tel_ila_dual_128.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/tel_icon.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_256x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_2kx15.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_32x16_single.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_32x16_single_modified.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/tel_ila.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_4kx14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_1kx18.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/myfifo2.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/aligner_rom_128x8.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_256x14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_16x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_64x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_16x13.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_1kx24.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_4kx16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_16x12.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/aligner_ram_128x8.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/tel_ila_36.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/spi_adc_rom.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_128x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/tel_ila_blknrj.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_8kx14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_1kx14.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/tel_ila_trig64.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/ram_32x16.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/myfifo.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {../common/ipcore_dir/tel_ila_128.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {ipcore_dir/get_icon.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {ipcore_dir/micro_wire_rom.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {ipcore_dir/get_ila.ncf}] -fileset [get_property constrset [current_run]]
add_files [list {ipcore_dir/myfifo.ncf}] -fileset [get_property constrset [current_run]]
set_property target_constrs_file "/home/fazia/Desktop/debug_fazia_code_roms/common/telescope.ucf" [current_fileset -constrset]
add_files [list {/home/fazia/Desktop/debug_fazia_code_roms/common/telescope.ucf}] -fileset [get_property constrset [current_run]]
link_design
